# Generated by Django 4.0.1 on 2022-01-15 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 1, 15, 15, 2, 50, 361053, tzinfo=utc))),
            ],
        ),
    ]
